### PR TITLE
Feature/fp21 132 404 page animation

### PR DESCRIPTION
**Pull request by hassou2n**
# Description

I created a 404 page and made the animation, and learned the plane is flying, I linked the button to the home page, when the user presses the (BACK HOME), it will turn it to the home page
KP image made as component and added only to needed pages
**back home** button added to ToolsDetails page

Fixes # (issue)

# How to test?

Run the frontend and go to this link [](http://localhost:3000/tools/111) or run the fronted and backend and try to jump to tool, which does not exist by changing the link and putting random numbers.

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by mag-da-lenka — CHANGES_REQUESTED** [review]
Hello @hassou2n 
Thanks for fast reaction. I have updated the speed and % phases of the animation.   
What's left for you to do is button styling. :)

**Review by alina-kho — COMMENTED** [review]
Besides what Magda has mentioned, please check routing for the 404 page. A user may simply make a typo in the path and it leads not to the 404 component page, but to something completely different.

**Comment by oleksandra-lavryk** [comment]
> Besides what Magda has mentioned, please check routing for the 404 page. A user may simply make a typo in the path and it leads not to the 404 component page, but to something completely different.

Fixed :white_check_mark:

**Comment by oleksandra-lavryk** [comment]
> Besides what Magda has mentioned, please check routing for the 404 page. A user may simply make a typo in the path and it leads not to the 404 component page, but to something completely different.

Fixed ✅

**Review by mag-da-lenka — APPROVED** [review]

**Review by alina-kho — APPROVED** [review]
Awesome 👍🏼

**Pull request merged**
