### PR TITLE
Heroku – Add database missing migration step to postbuild step

### PR DESCRIPTION
**Pull request by te-online**
# Description

Adds database setup/migration step to heroku-postbuild step

# How to test?

Change branch in Heroku. I will do this shortly.

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by ricardoaguiar — APPROVED** [review]

**Review by ricardoaguiar — CHANGES_REQUESTED** [review]
ops. it failed. I was too fast on the trigger.

**Comment by te-online** [comment]
Should work now 👍

**Review by shpomp — APPROVED** [review]
Works 🤩

**Review by alina-kho — APPROVED** [review]

**Comment by te-online** [comment]
@dpfernandes Review apps broke, because they don't have a database. Is it still okay to merge? 

Edit: Review apps will be disabled, so we can disregard the errors for now.

**Review by ricardoaguiar — APPROVED** [review]

**Pull request merged**
